# Generated by Django 3.0 on 2020-08-10 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0002_product_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackPrice',
            new_name='WishList',
        ),
    ]
