# Generated by Django 3.0 on 2020-08-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200810_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-title',)},
        ),
    ]
