# Generated by Django 3.0 on 2020-08-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200810_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ('-added_date',)},
        ),
    ]
