# Generated by Django 3.0 on 2020-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20200811_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
