# Generated by Django 3.0 on 2020-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20200811_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.CharField(max_length=400),
        ),
    ]
