# Generated by Django 3.0 on 2020-08-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20200811_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
