# Generated by Django 3.0 on 2020-08-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-price',)},
        ),
    ]
